Creating navbar
informatyzacja/flashcards pull request #11
Opened 2023-08-01 15:30 UTC by Suchy702

Everything as in Figma, must change padding od Container in Layouts to make 100% wide navbar

2023-08-01 19:08 UTC, Omikorin commented
/preview

2023-08-01 19:12 UTC, Omikorin requested changes

2023-08-01 19:12 UTC, Omikorin commented on package.json
> +    "next": "^13.4.12"
remove this change, it's monorepo package.json

2023-08-01 19:12 UTC, Omikorin commented on pnpm-lock.yaml
revert this too, this change is from mistake

2023-08-01 19:12 UTC, Omikorin commented on pnpm-lock.yaml
revert this change too, it's a mistake

2023-08-01 19:12 UTC, Omikorin commented on frontend/src/components/Layout.tsx
> +          <Navbar />
`<Navbar />` should be at line 21 before `<Container>` opening

it's because `<chakra.main>` is a main content container where children component lives, navbar's place is before any content containers

2023-08-01 19:12 UTC, Omikorin commented on frontend/src/components/Layout.tsx
> +import Navbar from './Navbar';
`import Navbar from '@/components/Navbar';`

2023-08-01 20:01 UTC, Omikorin commented
/preview

2023-08-01 20:54 UTC, Omikorin requested changes

2023-08-01 20:54 UTC, Omikorin commented on frontend/src/components/Layout.tsx
> +        padding={0}
remove this padding modification

2023-08-01 20:54 UTC, Omikorin commented on frontend/src/components/Navbar.tsx
> +    <Box bg="#2397FF" px={10} boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)">
add here `w="100%"`

2023-08-01 20:57 UTC, Omikorin commented on frontend/src/components/Navbar.tsx
> +        </Box>
why this additional `Box`?

2023-08-02 15:29 UTC, Suchy702 commented on frontend/src/components/Layout.tsx
> +        padding={0}
If i do this navbar (and other components) will not span the full width of the page

2023-08-02 18:00 UTC, Omikorin commented on frontend/src/components/Layout.tsx
> +        padding={0}
check my next comment below, if Box has 100% width, we can make some padding for main content (like on every website)

2023-08-02 18:11 UTC, Suchy702 commented on frontend/src/components/Layout.tsx
> +        padding={0}
I won't work, check this
https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwCEBXbbCAOwBpcAxAGxgA8bCIXcAVZ7GgYUrYAhkgoxMuAL64AZpggpcAcgACYABZCA1piEBaYkgD0mGELDYlAHQo3mGHLkgUAzngCCaNLgC8uABQAlL4AfPg2uLim2MSYFAERkbgAPAIUwqLiuChCTADqPlbggiJimAB0MsT09EWyjEw+wACM0lBILmj0QgCehSAyDXWDzAAiSJj9kPTEKLYgIYlJKWxMS8u4AO79zQAMuwCkRevLAEYA5v0AxABMAMwAnADstLTH8RuRaI0tu5InSVO7AAypooBBtkVdt9cAAWGHwpi4aFIzDnU5Cfy7GjY5E48o3ACsgXen0WH0+yQYzFw6n6ADYUXUhPQkOcKABJbAwFAuKYwdLiOoAK2IbiQMh6aW56X6nXMMD0pxg2E2MAFRXJn2WyVWWu1Ou4TDwMkEwKQAC8YP1YUyQLghHyiqc6tMsP1NuokNzNQCDTIOhatEg-RtkkYjdh9Qbw3rQ+HqUxo0lY+xk+HpaVxPqSRR-hQQJIgA

2023-08-02 18:27 UTC, Omikorin commented on frontend/src/components/Layout.tsx
> +        padding={0}
https://play.chakra-ui.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFzAAsBDAa0xIBpcAhAV22wgDsaAxAGxgA8baIfXABVe2GgGFW2EkhYxMuAL64AZpggpcAcgACxcpQC09JAHpMMEmGzaAOiwe8MOQqwDOeAIJo0uALy4ABQAlAEAfPgOuLiW2PSYLMHRMbgAPOEpqekCPFnZuADu-nYgAIwADBUApKX52QBGAOYlIADEAEwAzACcAOzs7HVJBTFoPP7AlUr1qQ2CAMqkUBDFpRXjuAAsmzs8uBv7mE0NJEEVNBcHlwB0HQCsIcOjmSOjaVy8uEStAGyHpVwJE4SCaLAAktgYCh3K0wDAWFDMICAFb0TxIVQATykiIR2Fa7jQ1hgRgaMGwhRgCNKr1G2TSuTp9IZoh4eFU0gWSAAXjBWlsASAgbDSg1AZBOFhWoUiEgobTZizVEh3DyyEglQU0mY2dhmSydUytTrPjwDakjYILTE0riZHIFLgUCQeAB1OHSWTyTA3VT0TicQGqbgTKYqKCqtCcEhY1oh3jB0MAESQmE9nHoKEcIBtloMFBINxdcnCJZYOoLlGL3rzOvt3oUFp1zKeLBmLBASiAA

2023-08-02 18:29 UTC, Omikorin commented on frontend/src/components/Layout.tsx
> +        padding={0}
but u need to move navbar upper in dom tree (i said that in another discussion)

2023-08-07 11:59 UTC, Omikorin requested changes

2023-08-07 11:59 UTC, Omikorin commented on frontend/src/components/Layout.tsx
> +import Navbar from './Navbar';
```suggestion
import Navbar from '@/components/Navbar';
```

2023-08-07 11:59 UTC, Omikorin commented on package.json
> +    "next": "^13.4.12"
```suggestion
```

2023-08-07 21:33 UTC, merged